package br.com.senac.projeto_integrador_ii.gui;

import br.com.senac.projeto_integrador_ii.persistencia.Musica;
import br.com.senac.projeto_integrador_ii.persistencia.MusicaDAO;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class Listagem extends javax.swing.JFrame {
    
    private String filtroGeneroAtual; 
    
    public void setFiltroGeneroAtual(String genero) {
        this.filtroGeneroAtual = genero;
    }

    public String getFiltroGeneroAtual() {
        return filtroGeneroAtual;
    }

    public javax.swing.JTextField getTxtPesquisa() {
        return txtPesquisa;
    }
    
    public void geraAcessibilidade() {
            btnVoltar.setMnemonic(KeyEvent.VK_V);            
        }
    
    

    public Listagem() {
        initComponents();
        geraAcessibilidade();
    }
    
    public void carregarMusicas(String pratica, String filtro, String pesquisa) {
        
    MusicaDAO musicaDAO = new MusicaDAO();
    List<Musica> musicas;
    
    if (pesquisa != null && !pesquisa.isEmpty()) {
        musicas = musicaDAO.buscarPorGeneroETitulo(filtro, pesquisa);
    } else {
        musicas = musicaDAO.buscarPorGenero(filtro);
    }
    
    DefaultTableModel model = (DefaultTableModel) tblMusica.getModel();
    model.setRowCount(0); 
    model.setColumnCount(0); 
    model.addColumn("ID");
    model.addColumn("Título");
    model.addColumn("Banda");
    model.addColumn("Tom");
    model.addColumn("Gênero");
    model.addColumn("Semestre Iniciado");
    model.addColumn("URL");
    

    for (Musica m : musicas) {
        model.addRow(new Object[]
        {
            m.getId(), 
            m.getTitulo(), 
            m.getBanda(), 
            m.getTom(), 
            m.getGenero(), 
            m.getSemestre_iniciado(), 
            m.getUrl()}
        );
    }

    lblPratica.setText(pratica);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Roxo = new javax.swing.JPanel();
        Branco = new javax.swing.JPanel();
        lblPratica = new javax.swing.JLabel();
        lblPesquisa = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        scrlMusica = new javax.swing.JScrollPane();
        tblMusica = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Roxo.setBackground(new java.awt.Color(100, 0, 139));
        Roxo.setMaximumSize(new java.awt.Dimension(1440, 1024));
        Roxo.setMinimumSize(new java.awt.Dimension(1440, 1024));
        Roxo.setPreferredSize(new java.awt.Dimension(1440, 1024));

        Branco.setBackground(new java.awt.Color(255, 255, 255));
        Branco.setMaximumSize(new java.awt.Dimension(1188, 850));
        Branco.setMinimumSize(new java.awt.Dimension(1188, 850));
        Branco.setPreferredSize(new java.awt.Dimension(1188, 850));

        lblPratica.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        lblPratica.setText("Prática de ");
        lblPratica.setToolTipText("Prática escolhida");

        lblPesquisa.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblPesquisa.setText("Pesquisar uma música:");

        txtPesquisa.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        txtPesquisa.setToolTipText("Digite aqui uma música");
        txtPesquisa.setNextFocusableComponent(btnVoltar);
        txtPesquisa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisaCaretUpdate(evt);
            }
        });

        tblMusica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        scrlMusica.setViewportView(tblMusica);

        btnVoltar.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.setToolTipText("Aperte para voltar a tela de seleção");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout BrancoLayout = new javax.swing.GroupLayout(Branco);
        Branco.setLayout(BrancoLayout);
        BrancoLayout.setHorizontalGroup(
            BrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrancoLayout.createSequentialGroup()
                .addGroup(BrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BrancoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(BrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnVoltar)
                            .addGroup(BrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(scrlMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(BrancoLayout.createSequentialGroup()
                                    .addComponent(lblPesquisa)
                                    .addGap(27, 27, 27)
                                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(BrancoLayout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(lblPratica)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        BrancoLayout.setVerticalGroup(
            BrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrancoLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lblPratica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(BrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesquisa)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scrlMusica, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        lblPratica.getAccessibleContext().setAccessibleDescription("Texto centralizado no topo da tela com a prática escolhida");
        txtPesquisa.getAccessibleContext().setAccessibleDescription("Campo de texto para música");
        scrlMusica.getAccessibleContext().setAccessibleDescription("Tabela de músicas");
        btnVoltar.getAccessibleContext().setAccessibleDescription("Botão para voltar a tela de seleção");

        javax.swing.GroupLayout RoxoLayout = new javax.swing.GroupLayout(Roxo);
        Roxo.setLayout(RoxoLayout);
        RoxoLayout.setHorizontalGroup(
            RoxoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RoxoLayout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addComponent(Branco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
        RoxoLayout.setVerticalGroup(
            RoxoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RoxoLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(Branco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Roxo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Roxo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtPesquisaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisaCaretUpdate
    String textoPesquisa = txtPesquisa.getText().trim();
    carregarMusicas("Prática de " + filtroGeneroAtual, filtroGeneroAtual, textoPesquisa);

    }//GEN-LAST:event_txtPesquisaCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Listagem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Listagem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Branco;
    private javax.swing.JPanel Roxo;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblPesquisa;
    public javax.swing.JLabel lblPratica;
    private javax.swing.JScrollPane scrlMusica;
    private javax.swing.JTable tblMusica;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
