package br.com.senac.projeto_integrador_ii.gui;

import br.com.senac.projeto_integrador_ii.persistencia.Usuario;
import br.com.senac.projeto_integrador_ii.service.AuthService;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    public Login() {
        initComponents();
        geraAcessibilidade();
    }
    
    public void geraAcessibilidade() {
            btnLogin.setMnemonic(KeyEvent.VK_D);
            btnEsqueceu.setMnemonic(KeyEvent.VK_F);            
        }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        Branco = new javax.swing.JPanel();
        lblBemVindo = new javax.swing.JLabel();
        lblPorFavor = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        btnEsqueceu = new javax.swing.JButton();
        btnLogin = new javax.swing.JButton();
        lblNaoe = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        Roxo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Branco.setBackground(new java.awt.Color(255, 255, 255));
        Branco.setPreferredSize(new java.awt.Dimension(720, 1024));

        lblBemVindo.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        lblBemVindo.setText("Bem-vindo (a) novamente!");
        lblBemVindo.setToolTipText("Bem-vindo (a) novamente!");

        lblPorFavor.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblPorFavor.setText("Por favor insira os seus dados para realizar o login");
        lblPorFavor.setToolTipText("Por favor insira os seus dados para realizar o login");

        lblEmail.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblEmail.setText("Email");

        txtEmail.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtEmail.setToolTipText("Digite aqui o email ");
        txtEmail.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        txtEmail.setNextFocusableComponent(txtSenha);

        lblSenha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        lblSenha.setText("Senha");

        btnEsqueceu.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        btnEsqueceu.setForeground(new java.awt.Color(100, 0, 139));
        btnEsqueceu.setText("Esqueceu a senha?");
        btnEsqueceu.setToolTipText("Selecione caso tenha esquecido a senha");
        btnEsqueceu.setBorder(null);
        btnEsqueceu.setNextFocusableComponent(btnLogin);
        btnEsqueceu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEsqueceuActionPerformed(evt);
            }
        });

        btnLogin.setBackground(new java.awt.Color(100, 0, 139));
        btnLogin.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Login");
        btnLogin.setToolTipText("Aperte para realizar o login");
        btnLogin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(100, 0, 139), 1, true));
        btnLogin.setPreferredSize(new java.awt.Dimension(400, 60));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        lblNaoe.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        lblNaoe.setForeground(new java.awt.Color(182, 176, 176));
        lblNaoe.setText("Não é cadastrado? Mande mensagem para a secretaria");
        lblNaoe.setToolTipText("Não é cadastrado? Mande mensagem para a secretaria");

        txtSenha.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        txtSenha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout BrancoLayout = new javax.swing.GroupLayout(Branco);
        Branco.setLayout(BrancoLayout);
        BrancoLayout.setHorizontalGroup(
            BrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BrancoLayout.createSequentialGroup()
                .addGap(0, 115, Short.MAX_VALUE)
                .addComponent(lblNaoe)
                .addGap(112, 112, 112))
            .addGroup(BrancoLayout.createSequentialGroup()
                .addGroup(BrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BrancoLayout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(BrancoLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addGroup(BrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblSenha)
                            .addComponent(txtEmail)
                            .addComponent(lblEmail)
                            .addComponent(lblPorFavor)
                            .addComponent(lblBemVindo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(BrancoLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(btnEsqueceu))
                            .addComponent(txtSenha))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BrancoLayout.setVerticalGroup(
            BrancoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BrancoLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addComponent(lblBemVindo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPorFavor)
                .addGap(100, 100, 100)
                .addComponent(lblEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(lblSenha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(btnEsqueceu)
                .addGap(37, 37, 37)
                .addComponent(btnLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(lblNaoe)
                .addContainerGap(222, Short.MAX_VALUE))
        );

        lblBemVindo.getAccessibleContext().setAccessibleDescription("Texto centralizado no topo da tela com a mensagem \"Bem-vindo (a) novamente!\"");
        lblPorFavor.getAccessibleContext().setAccessibleDescription("Texto centralizado no topo da tela com a mensagem \"Por favor insira os seus dados para realizar o login\"");
        txtEmail.getAccessibleContext().setAccessibleDescription("Campo de texto para o email");
        btnEsqueceu.getAccessibleContext().setAccessibleDescription("Botao para realizar a troca de senha");
        btnLogin.getAccessibleContext().setAccessibleDescription("Botão para realizar o login");
        lblNaoe.getAccessibleContext().setAccessibleDescription("Texto centralizado no fim da tela com a mensagem \"Não é cadastrado? Mande mensagem para a secretaria\"");

        Roxo.setBackground(new java.awt.Color(100, 0, 139));
        Roxo.setPreferredSize(new java.awt.Dimension(720, 1024));

        javax.swing.GroupLayout RoxoLayout = new javax.swing.GroupLayout(Roxo);
        Roxo.setLayout(RoxoLayout);
        RoxoLayout.setHorizontalGroup(
            RoxoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 720, Short.MAX_VALUE)
        );
        RoxoLayout.setVerticalGroup(
            RoxoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1024, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addComponent(Branco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Roxo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Branco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Roxo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEsqueceuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEsqueceuActionPerformed
        JOptionPane.showMessageDialog(null, "Mande mensagem para a secretaria (11) 99123-4567");
    }//GEN-LAST:event_btnEsqueceuActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        AuthService authService = new AuthService();
        Usuario usuario = authService.autenticar(txtEmail.getText(), txtSenha.getText());

        if (usuario == null) {
            JOptionPane.showMessageDialog(this, "Erro de autenticação! Verifique seus dados.");
            return;
        }

        Seleção seleção = new Seleção();
        configurarPermissoes(usuario, seleção);

        JOptionPane.showMessageDialog(this, "Bem-vindo, " + usuario.getTipo() + "!");
        seleção.setUsuario(usuario);
        seleção.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void configurarPermissoes(Usuario usuario, Seleção seleção) {
        boolean isProfessor = usuario.getTipo().equalsIgnoreCase("professor");
        seleção.btnGerenciar.setEnabled(isProfessor);
        seleção.btnSair.setEnabled(true);
        seleção.btnRock.setEnabled(true);
        seleção.btnBlackMusic.setEnabled(true);
        seleção.btnSertanejo.setEnabled(true);
        seleção.btnPop.setEnabled(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Branco;
    private javax.swing.JPanel Login;
    private javax.swing.JPanel Roxo;
    private javax.swing.JButton btnEsqueceu;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNaoe;
    private javax.swing.JLabel lblPorFavor;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
